# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'SWAPI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SWAPI
pod 'SwiftLint'
pod 'Alamofire'

  target 'SWAPITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SWAPIUITests' do
    # Pods for testing
  end

end
